WARNING:tensorflow:From /home/y20212721/tools/miniconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow_core/python/compat/v2_compat.py:88: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
WARNING:tensorflow:From /home/y20212721/Youngtop/code_ja_relation/include/Model.py:388: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
Traceback (most recent call last):
  File "/home/y20212721/tools/miniconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1367, in _do_call
    return fn(*args)
  File "/home/y20212721/tools/miniconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1352, in _run_fn
    target_list, run_metadata)
  File "/home/y20212721/tools/miniconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1445, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'neg2_right' with dtype int32 and shape [?]
	 [[{{node neg2_right}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 112, in <module>
    build(config.dim, config.act_func, config.gamma, config.k, config.vec, e,e1,e2,ILL_r, KG1,KG2,KG1 + KG2)
  File "/home/y20212721/Youngtop/code_ja_relation/include/Model.py", line 979, in build
    loss_pre, loss_transr=sess.run([loss_pre,loss_transr])
  File "/home/y20212721/tools/miniconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 960, in run
    run_metadata_ptr)
  File "/home/y20212721/tools/miniconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1183, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/y20212721/tools/miniconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1361, in _do_run
    run_metadata)
  File "/home/y20212721/tools/miniconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1386, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'neg2_right' with dtype int32 and shape [?]
	 [[node neg2_right (defined at /home/y20212721/Youngtop/code_ja_relation/include/Model.py:966) ]]

Original stack trace for 'neg2_right':
  File "main.py", line 112, in <module>
    build(config.dim, config.act_func, config.gamma, config.k, config.vec, e,e1,e2,ILL_r, KG1,KG2,KG1 + KG2)
  File "/home/y20212721/Youngtop/code_ja_relation/include/Model.py", line 966, in build
    neg2_right = tf.placeholder(tf.int32, [None], "neg2_right")
  File "/home/y20212721/tools/miniconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow_core/python/ops/array_ops.py", line 2718, in placeholder
    return gen_array_ops.placeholder(dtype=dtype, shape=shape, name=name)
  File "/home/y20212721/tools/miniconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_array_ops.py", line 6032, in placeholder
    "Placeholder", dtype=dtype, shape=shape, name=name)
  File "/home/y20212721/tools/miniconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow_core/python/framework/op_def_library.py", line 742, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
  File "/home/y20212721/tools/miniconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3322, in _create_op_internal
    op_def=op_def)
  File "/home/y20212721/tools/miniconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 1756, in __init__
    self._traceback = tf_stack.extract_stack()

